export default {
  //commmon

  SPLASH: 'SPLASH',
  CHOOSE_LANGUAGE: 'CHOOSE_LANGUAGE',
  ONBOARDING: 'ONBOARDING',
  WELCOME: 'WELCOME',
  REGISTER: 'REGISTER',
  HOME_SCREEN: 'HOME_SCREEN',
  CATEGORY: 'CATEGORY',
  CATEGORY_ITEM: 'CATEGORY_ITEM',
  CART: 'CART',
  WISHLIST: 'WISHLIST',
  ACCOUNT: 'ACCOUNT',
  TAB_NAVIGATOR: 'TAB_NAVIGATOR',
  PRODUCT: 'PRODUCT',
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  OTP_VERIFICATION: 'OTP_VERIFICATION',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD',
  HOME_SCREEN: 'HOME_SCREEN',
};
